window.NCERT_CURRICULUM_2026_27 = {
  "6": {
    "mathematics": ["Ch 1: Patterns in Mathematics", "Ch 2: Lines and Angles", "Ch 3: Number Play", "Ch 4: Data Handling and Presentation", "Ch 5: Prime Time", "Ch 6: Perimeter and Area", "Ch 7: Fractions", "Ch 8: Playing with Constructions", "Ch 9: Symmetry", "Ch 10: The Other Side of Zero"],
    "science": ["Ch 1: The Wonderful World of Science", "Ch 2: Diversity in the Living World", "Ch 3: Mindful Eating: A Path to a Healthy Body", "Ch 4: Exploring Magnets", "Ch 5: Measurement of Length and Motion", "Ch 6: Materials Around Us", "Ch 7: Temperature and its Measurement", "Ch 8: A Journey through States of Water", "Ch 9: Methods of Separation in Everyday Life", "Ch 10: Living Creatures: Exploring their Characteristics", "Ch 11: Nature’s Treasures", "Ch 12: Beyond Earth"],
    "english": ["Unit 1: A Bottle of Dew", "Unit 1: The Raven and the Fox", "Unit 1: Rama to the Rescue", "Unit 2: The Unlikely Best Friends", "Unit 2: A Friend's Prayer", "Unit 2: The Chair", "Unit 3: Neem Baba", "Unit 3: What a Bird Thought", "Unit 3: Spices that Heal Us", "Unit 4: Change of Heart", "Unit 4: The Winner", "Unit 4: Yoga—A Way of Life", "Unit 5: Hamara Bharat—Incredible India!", "Unit 5: The Kites", "Unit 5: Ila Sachani: Embroidering Dreams", "Unit 5: National War Memorial"],
    "social-science": ["Ch 1: Locating Places on the Earth", "Ch 2: Oceans and Continents", "Ch 3: Landforms and Life", "Ch 4: Timeline and Sources of History", "Ch 5: India, That Is Bharat", "Ch 6: The Beginnings of Indian Civilisation", "Ch 7: India's Cultural Roots", "Ch 8: Unity in Diversity", "Ch 9: Family and Community", "Ch 10: Grassroots Democracy - Governance", "Ch 11: Local Government in Rural Areas", "Ch 12: Local Government in Urban Areas", "Ch 13: The Value of Work", "Ch 14: Economic Activities Around Us"]
  },
  "7": {
    "mathematics": ["Ch 1: Large Numbers Around Us", "Ch 2: Arithmetic Expressions", "Ch 3: A Peek Beyond the Point", "Ch 4: Expressions using Letter-Numbers", "Ch 5: Parallel and Intersecting Lines", "Ch 6: Number Play", "Ch 7: A Tale of Three Intersecting Lines", "Ch 8: Working with Fractions", "Ch 9: Geometric Twins", "Ch 10: Operations with Integers", "Ch 11: Finding Common Ground", "Ch 12: Another Peek Beyond the Point", "Ch 13: Connecting the Dots...", "Ch 14: Constructions and Tilings", "Ch 15: Finding the Unknown"],
    "science": ["Ch 1: The Ever-Evolving World of Science", "Ch 2: Exploring Substances: Acidic, Basic, and Neutral", "Ch 3: Electricity: Circuits and their Components", "Ch 4: The World of Metals and Non-metals", "Ch 5: Changes Around Us: Physical and Chemical", "Ch 6: Adolescence: A Stage of Growth and Change", "Ch 7: Heat Transfer in Nature", "Ch 8: Measurement of Time and Motion", "Ch 9: Life Processes in Animals", "Ch 10: Life Processes in Plants", "Ch 11: Light: Shadows and Reflections", "Ch 12: Earth, Moon, and the Sun"],
    "english": ["Unit 1: The Day the River Spoke", "Unit 1: Try Again", "Unit 1: Three Days to See", "Unit 2: Animals, Birds, and Dr. Dolittle", "Unit 2: A Funny Man", "Unit 2: Say the Right Thing", "Unit 3: My Brother's Great Invention", "Unit 3: Paper Boats", "Unit 3: North, South, East, West", "Unit 4: The Tunnel", "Unit 4: Travel", "Unit 4: Conquering the Summit", "Unit 5: A Homage to Our Brave Soldiers", "Unit 5: My Dear Soldiers", "Unit 5: Rani Abbakka"],
    "social-science": ["Ch 1: Geographical Diversity of India", "Ch 2: Understanding the Weather", "Ch 3: Climates of India", "Ch 4: New Beginnings: Cities and States", "Ch 5: The Rise of Empires", "Ch 6: The Age of Reorganisation", "Ch 7: The Gupta Era", "Ch 8: How the Land Becomes Sacred", "Ch 9: From the Rulers to the Ruled", "Ch 10: The Story of Indian Farming", "Ch 11: India and Her Neighbours", "Ch 12: Empires and Kingdoms", "Ch 13: Turning Tides", "Ch 14: India, a Home to Many", "Ch 15: The State, the Government, and You", "Ch 16: Infrastructure: Engine of Development", "Ch 17: Banks and the Magic of Finance"]
  },
  "8": {
    "mathematics": ["Ch 1: A Square and A Cube", "Ch 2: Power Play", "Ch 3: A Story of Numbers", "Ch 4: Quadrilaterals", "Ch 5: Number Play", "Ch 6: We Distribute, Yet Things Multiply", "Ch 7: Proportional Reasoning-1", "Ch 8: Fractions in Disguise", "Ch 9: The Baudhayana-Pythagoras Theorem", "Ch 10: Proportional Reasoning-2", "Ch 11: Exploring Some Geometric Themes", "Ch 12: Tales by Dots and Lines", "Ch 13: Algebra Play", "Ch 14: Area"],
    "science": ["Ch 1: Exploring the Investigative World of Science", "Ch 2: The Invisible Living World: Beyond Our Naked Eye", "Ch 3: BULLETIN BOARD", "Ch 4: Electricity: Magnetic and Heating Effects", "Ch 5: Exploring Forces", "Ch 6: Pressure, Winds, Storms, and Cyclones", "Ch 7: Particulate Nature of Matter", "Ch 8: Nature of Matter", "Ch 9: Solutes, Solvents, and Solutions", "Ch 10: Light: Mirrors and Lenses", "Ch 11: Keeping Time", "Ch 12: How Nature Works in Harmony", "Ch 13: Our Home"],
    "english": ["Unit 1: The Wit that Won Hearts", "Unit 1: A Concrete Example", "Unit 1: Wisdom Paves the Way", "Unit 2: Major Somnath Sharma & Battle of Badgam", "Unit 2: Somebody's Mother", "Unit 2: Verghese Kurien—I Too Had A Dream", "Unit 3: The Case of the Fifth Word", "Unit 3: The Magic Brush of Dreams", "Unit 3: Spectacular Wonders", "Unit 4: The Cherry Tree", "Unit 4: Harvest Hymn", "Unit 4: Waiting for the Rain", "Unit 5: Feathered Friend", "Unit 5: Magnifying Glass", "Unit 5: Bibha Chowdhuri: Beam of Light"],
    "social-science": ["Ch 1: Natural Resources and Their Use", "Ch 2: Reshaping India's Political Map", "Ch 3: The Rise of the Marathas", "Ch 4: The Colonial Era in India", "Ch 5: Universal Franchise & Electoral System", "Ch 6: The Parliamentary System", "Ch 7: Factors of Production", "Ch 8: World Geography: Some Glimpses", "Ch 9: India's Long Road to Independence", "Ch 10: Indian Architecture", "Ch 11: The Role of the Judiciary", "Ch 12: Citizenship: Rights and Duties", "Ch 13: Dynamics of Population", "Ch 14: India's Urban Landscape", "Ch 15: Cultural Currents"]
  },
  "9": {
    "mathematics": ["Ch 1: Orienting Yourself: The Use of Coordinates", "Ch 2: Introduction to Linear Polynomials", "Ch 3: The World of Numbers", "Ch 4: Exploring Algebraic Identities", "Ch 5: I’m Up and Down, and Round and Round", "Ch 6: Measuring Space: Perimeter and Area", "Ch 7: Introduction to Probability", "Ch 8: Sequences and Progressions"],
    "science": ["Ch 1: Entering the World of Secondary Science", "Ch 2: Cell: The Building Block of Life", "Ch 3: Tissues in Action", "Ch 4: Describing Motion Around Us", "Ch 5: Exploring Mixtures and their Separation", "Ch 6: How Forces Affect Motion", "Ch 7: Work, Energy and Simple Machines", "Ch 8: Journey Inside the Atom", "Ch 9: Atomic Foundation of Matter", "Ch 10: Sound Waves: Characteristics & Applications", "Ch 11: Reproduction – How Life Continues", "Ch 12: Diversity and Classification", "Ch 13: Earth as a System"],
    "english": ["Ch 1: How I Taught My Grandmother to Read", "Ch 1: Bharat Our Land", "Ch 2: The Pot Maker", "Ch 2: Gifts of Grace", "Ch 3: Winds of Change", "Ch 3: Canvas of Soil", "Ch 4: Vitamin-M", "Ch 4: I Cannot Remember My Mother", "Ch 5: Limitless Possibilities", "Ch 5: Nine Gold Medals", "Ch 6: Twin Melodies", "Ch 6: A Friend Found in Music", "Ch 7: Carrier of Words", "Ch 7: Words", "Ch 8: Follow That Dream", "Ch 8: Believe in Yourself"],
    "social-science": ["Ch 1: Understanding Social Science", "Ch 2: Shaping of the Earth's Surface", "Ch 3: Atmosphere and Climate", "Ch 4: Early Humans & Beginning of Civilisation", "Ch 5: State and Society up to 1000 CE", "Ch 6: Democracy", "Ch 7: Elections", "Ch 8: Building Blocks in Economics", "Ch 9: The Price Puzzle: What Drives Market"]
  },
  "10": {
    "mathematics": ["Ch 1: Real Numbers", "Ch 2: Polynomials", "Ch 3: Pair of Linear Equations in Two Variables", "Ch 4: Quadratic Equations", "Ch 5: Arithmetic Progressions", "Ch 6: Triangles", "Ch 7: Coordinate Geometry", "Ch 8: Introduction to Trigonometry", "Ch 9: Some Applications of Trigonometry", "Ch 10: Circles", "Ch 11: Areas Related to Circles", "Ch 12: Surface Areas and Volumes", "Ch 13: Statistics", "Ch 14: Probability"],
    "science": ["Ch 1: Chemical Reactions and Equations", "Ch 2: Acids, Bases and Salts", "Ch 3: Metals and Non-metals", "Ch 4: Carbon and its Compounds", "Ch 5: Life Processes", "Ch 6: Control and Coordination", "Ch 7: How do Organisms Reproduce?", "Ch 8: Heredity and Evolution", "Ch 9: Light – Reflection and Refraction", "Ch 10: Human Eye and Colourful World", "Ch 11: Electricity", "Ch 12: Magnetic Effects of Electric Current", "Ch 13: Our Environment"],
    "english": ["Prose: A Letter to God", "Prose: Nelson Mandela: Long Walk to Freedom", "Prose: Two Stories about Flying", "Prose: From the Diary of Anne Frank", "Prose: Glimpses of India", "Prose: Mijbil the Otter", "Prose: Madam Rides the Bus", "Prose: The Sermon at Benares", "Prose: The Proposal", "Poem: Dust of Snow", "Poem: Fire and Ice", "Poem: A Tiger in the Zoo", "Poem: Amanda!", "Reader: A Triumph of Surgery", "Reader: The Thief's Story", "Reader: Footprints without Feet", "Reader: The Necklace", "Reader: Bholi"],
    "social-science": ["Geo: Resources and Development", "Geo: Forest and Wildlife Resources", "Geo: Water Resources", "Geo: Agriculture", "Geo: Minerals and Energy Resources", "Geo: Manufacturing Industries", "Hist: The Rise of Nationalism in Europe", "Hist: Nationalism in India", "Hist: The Making of a Global World", "Hist: Print Culture and Modern World", "Pol: Power-sharing", "Pol: Federalism", "Pol: Gender, Religion and Caste", "Pol: Political Parties", "Eco: Development", "Eco: Sectors of Indian Economy", "Eco: Money and Credit", "Eco: Globalisation"]
  },
  "11": {
    "english": ["Hor: The Portrait of a Lady", "Hor: We're Not Afraid to Die...", "Hor: Discovering Tut: Saga Continues", "Hor: The Ailing Planet", "Hor: The Adventure", "Hor: Silk Road", "Poem: A Photograph", "Poem: The Laburnum Top", "Poem: The Voice of the Rain", "Poem: Childhood", "Poem: Father to Son", "Snap: Summer of Beautiful White Horse", "Snap: The Address", "Snap: Mother's Day", "Snap: Birth"],
    "science-mathematics": ["Ch 1: Sets", "Ch 2: Relations and Functions", "Ch 3: Trigonometric Functions", "Ch 4: Complex Numbers & Quadratic Eq", "Ch 5: Linear Inequalities", "Ch 6: Permutations and Combinations", "Ch 7: Binomial Theorem", "Ch 8: Sequences and Series", "Ch 9: Straight Lines", "Ch 10: Conic Sections", "Ch 11: 3D Geometry", "Ch 12: Limits and Derivatives", "Ch 13: Statistics", "Ch 14: Probability"],
    "science-physics": ["Ch 1: Units and Measurements", "Ch 2: Motion in a Straight Line", "Ch 3: Motion in a Plane", "Ch 4: Laws of Motion", "Ch 5: Work, Energy and Power", "Ch 6: Rotational Motion", "Ch 7: Gravitation", "Ch 8: Properties of Solids", "Ch 9: Properties of Fluids", "Ch 10: Thermal Properties", "Ch 11: Thermodynamics", "Ch 12: Kinetic Theory", "Ch 13: Oscillations", "Ch 14: Waves"],
    "science-chemistry": ["Ch 1: Basic Concepts of Chemistry", "Ch 2: Structure of Atom", "Ch 3: Classification of Elements", "Ch 4: Chemical Bonding & Molecular Struct", "Ch 5: Thermodynamics", "Ch 6: Equilibrium", "Ch 7: Redox Reactions", "Ch 8: Organic Chemistry Basics", "Ch 9: Hydrocarbons"],
    "commerce-accountancy": ["Ch 1: Introduction to Accounting", "Ch 2: Theory Base of Accounting", "Ch 3: Recording of Transactions - I", "Ch 4: Recording of Transactions - II", "Ch 5: Bank Reconciliation Statement", "Ch 6: Trial Balance & Rectification", "Ch 7: Depreciation & Reserves", "Ch 8: Financial Statements - I", "Ch 9: Financial Statements - II", "Ch 10: Incomplete Records", "Ch 11: Computerised Accounting System"],
    "commerce-economics": ["Ch 1: Introduction to Statistics", "Ch 2: Collection of Data", "Ch 3: Organisation of Data", "Ch 4: Presentation of Data", "Ch 5: Measures of Central Tendency", "Ch 6: Correlation", "Ch 7: Index Numbers", "Ch 8: Microeconomics Intro", "Ch 9: Consumer's Equilibrium", "Ch 10: Demand & Elasticity", "Ch 11: Production Function & Cost", "Ch 12: Market Forms & Price Determination"],
    "commerce-business-studies": ["Ch 1: Business, Trade and Commerce", "Ch 2: Forms of Business Organisation", "Ch 3: Private, Public & Global Enterprises", "Ch 4: Business Services", "Ch 5: Emerging Modes of Business", "Ch 6: Social Responsibilities & Ethics", "Ch 7: Formation of a Company", "Ch 8: Sources of Business Finance", "Ch 9: Small Business & Entrepreneurship", "Ch 10: Internal Trade", "Ch 11: International Business"],
    "humanities-political-science": ["Ch 1: Constitution: Why and How?", "Ch 2: Rights in Indian Constitution", "Ch 3: Election and Representation", "Ch 4: Executive", "Ch 5: Legislature", "Ch 6: Judiciary", "Ch 7: Federalism", "Ch 8: Local Governments", "Ch 9: Constitution as Living Document", "Ch 10: Political Theory Intro", "Ch 11: Freedom & Equality", "Ch 12: Social Justice & Rights", "Ch 13: Citizenship & Nationalism", "Ch 14: Secularism"],
    "humanities-history": ["Ch 1: Writing and City Life", "Ch 2: An Empire Across Three Continents", "Ch 3: Nomadic Empires", "Ch 4: The Three Orders", "Ch 5: Changing Cultural Traditions", "Ch 6: Displacing Indigenous Peoples", "Ch 7: Paths to Modernisation"],
    "humanities-geography": ["Ch 1: Geography as a Discipline", "Ch 2: Origin and Evolution of Earth", "Ch 3: Interior of the Earth", "Ch 4: Distribution of Oceans & Continents", "Ch 5: Geomorphic Processes", "Ch 6: Landforms & Evolution", "Ch 7: Atmosphere & Climate", "Ch 8: Water & Oceans", "Ch 9: India - Location & Physiography", "Ch 10: Drainage System & Climate"],
    "humanities-hindi-core": ["Ch 1: नमक का दारोगा", "Ch 2: मियाँ नसीरुद्दीन", "Ch 3: अपू के साथ ढाई साल", "Ch 4: विदाई-संभाषण", "Ch 5: गलता लोहा", "Ch 6: रजनी", "Ch 7: जामुन का पेड़", "Ch 8: भारत माता", "Ch 9: घर की याद", "Ch 10: चंपा काले-काले अच्छर नहीं चीन्हती", "Ch 11: राजस्थान की रजत बूँदें", "Ch 12: आलो-आँधारि"]
  },
  "12": {
    "english": ["Flam: The Last Lesson", "Flam: Lost Spring", "Flam: Deep Water", "Flam: The Rattrap", "Flam: Indigo", "Flam: Poets and Pancakes", "Flam: The Interview", "Flam: Going Places", "Poem: My Mother at Sixty-six", "Poem: Keeping Quiet", "Poem: A Thing of Beauty", "Poem: A Roadside Stand", "Poem: Aunt Jennifer's Tigers", "Vistas: The Third Level", "Vistas: The Tiger King", "Vistas: Journey to End of Earth", "Vistas: The Enemy", "Vistas: On the Face of It", "Vistas: Memories of Childhood"],
    "science-mathematics": ["Ch 1: Relations and Functions", "Ch 2: Inverse Trigonometric Functions", "Ch 3: Matrices", "Ch 4: Determinants", "Ch 5: Continuity and Differentiability", "Ch 6: Application of Derivatives", "Ch 7: Integrals", "Ch 8: Application of Integrals", "Ch 9: Differential Equations", "Ch 10: Vector Algebra", "Ch 11: Three Dimensional Geometry", "Ch 12: Linear Programming", "Ch 13: Probability"],
    "science-physics": ["Ch 1: Electric Charges and Fields", "Ch 2: Electrostatic Potential & Capacitance", "Ch 3: Current Electricity", "Ch 4: Moving Charges and Magnetism", "Ch 5: Magnetism and Matter", "Ch 6: Electromagnetic Induction", "Ch 7: Alternating Current", "Ch 8: Electromagnetic Waves", "Ch 9: Ray Optics & Instruments", "Ch 10: Wave Optics", "Ch 11: Dual Nature of Radiation & Matter", "Ch 12: Atoms & Nuclei", "Ch 13: Semiconductor Electronics"],
    "science-chemistry": ["Ch 1: Solutions", "Ch 2: Electrochemistry", "Ch 3: Chemical Kinetics", "Ch 4: The d- and f-Block Elements", "Ch 5: Coordination Compounds", "Ch 6: Haloalkanes and Haloarenes", "Ch 7: Alcohols, Phenols and Ethers", "Ch 8: Aldehydes, Ketones & Carboxylic Acids", "Ch 9: Amines", "Ch 10: Biomolecules"],
    "commerce-accountancy": ["Ch 1: Accounting for Partnership", "Ch 2: Admission of a Partner", "Ch 3: Retirement/Death of a Partner", "Ch 4: Dissolution of Partnership Firm", "Ch 5: Accounting for Share Capital", "Ch 6: Issue & Redemption of Debentures", "Ch 7: Financial Statements of Company", "Ch 8: Accounting Ratios", "Ch 9: Cash Flow Statement"],
    "commerce-economics": ["Ch 1: Macroeconomics Intro", "Ch 2: National Income Accounting", "Ch 3: Money and Banking", "Ch 4: Income and Employment", "Ch 5: Government Budget & Economy", "Ch 6: Open Economy Macroeconomics", "Ch 7: Indian Economy on Eve of Independence", "Ch 8: Indian Economy 1950-1990", "Ch 9: LPG Reforms Appraisal", "Ch 10: Human Capital Formation", "Ch 11: Rural Development", "Ch 12: Employment & Informalisation", "Ch 13: Sustainable Development"],
    "commerce-business-studies": ["Ch 1: Nature & Significance of Management", "Ch 2: Principles of Management", "Ch 3: Business Environment", "Ch 4: Planning", "Ch 5: Organising", "Ch 6: Staffing", "Ch 7: Directing", "Ch 8: Controlling", "Ch 9: Financial Management", "Ch 10: Financial Markets", "Ch 11: Marketing", "Ch 12: Consumer Protection"],
    "humanities-political-science": ["Ch 1: The End of Bipolarity", "Ch 2: Contemporary Centres of Power", "Ch 3: Contemporary South Asia", "Ch 4: International Organizations", "Ch 5: Security in Contemporary World", "Ch 6: Environment & Natural Resources", "Ch 7: Globalisation", "Ch 8: Challenges of Nation-Building", "Ch 9: Era of One-Party Dominance", "Ch 10: Politics of Planned Development", "Ch 11: India's External Relations", "Ch 12: Challenges to Congress System", "Ch 13: Crisis of Democratic Order", "Ch 14: Regional Aspirations", "Ch 15: Recent Developments in Indian Politics"],
    "humanities-history": ["Ch 1: Bricks, Beads and Bones (Harappan)", "Ch 2: Kings, Farmers and Towns", "Ch 3: Kinship, Caste and Class", "Ch 4: Thinkers, Beliefs and Buildings", "Ch 5: Through the Eyes of Travellers", "Ch 6: Bhakti-Sufi Traditions", "Ch 7: Vijayanagara", "Ch 8: Peasants, Zamindars and State", "Ch 9: Colonialism and Countryside", "Ch 10: Rebels and the Raj (1857)", "Ch 11: Mahatma Gandhi & Nationalist Movement", "Ch 12: Framing the Constitution"],
    "humanities-geography": ["Ch 1: Human Geography: Nature & Scope", "Ch 2: World Population Distribution & Growth", "Ch 3: Human Development", "Ch 4: Primary & Secondary Activities", "Ch 5: Tertiary & Quaternary Activities", "Ch 6: Transport, Communication & Trade", "Ch 7: International Trade", "Ch 8: Population of India", "Ch 9: Human Settlements", "Ch 10: Land & Water Resources", "Ch 11: Mineral & Energy Resources"],
    "humanities-hindi-core": ["Ch 1: आत्मपरिचय, एक गीत", "Ch 2: पतंग", "Ch 3: कविता के बहाने", "Ch 4: कैमरे में बंद अपाहिज", "Ch 5: सहर्ष स्वीकारा है", "Ch 6: उषा", "Ch 7: बादल राग", "Ch 8: लक्ष्मण-मूर्छा और राम का विलाप", "Ch 9: रुबाइयाँ, ग़ज़ल", "Ch 10: छोटा मेरा खेत", "Ch 11: भक्तिन", "Ch 12: बाजार दर्शन", "Ch 13: काले मेघा पानी दे", "Ch 14: पहलवान की ढोलक", "Ch 15: शिरीष के फूल", "Ch 16: श्रम-विभाजन और जाति-प्रथा", "Ch 17: सिल्वर वैडिंग", "Ch 18: जूझ", "Ch 19: अतीत में दबे पाँव"]
  }
};